Repository TeamBeMe/BeMeiOS, pull requests merged in 2021-01, with the labels that each got.

#26 Feature/#24 readme
  GitManage.md
  README.md
Labels: documentation, 윤재

#29 탐색 화면 만들었습니다.
  BeMe/BeMe.xcodeproj/project.pbxproj
  BeMe/BeMe/Assets.xcassets/background.colorset/Contents.json
  BeMe/BeMe/Assets.xcassets/profile.imageset/Contents.json
  BeMe/BeMe/Assets.xcassets/profile.imageset/profile.png
  BeMe/BeMe/Explore/Cells/ArticleTVC.swift
  BeMe/BeMe/Explore/Cells/CategoryCVC.swift
  BeMe/BeMe/Explore/Cells/CategoryTVC.swift
  BeMe/BeMe/Explore/Cells/DiffThoughtCVC.swift
  BeMe/BeMe/Explore/Cells/MoreTVC.swift
  BeMe/BeMe/Explore/Storyboards/Explore.storyboard
  BeMe/BeMe/Explore/VCs/ExploreVC.swift
  BeMe/BeMe/Extensions/UIButton+Extensions.swift
  BeMe/BeMe/Info.plist
  BeMe/BeMe/UnderTab/VCs/UnderTabBarController.swift
  BeMe/Podfile
  BeMe/Podfile.lock
Labels: view, 재용

#39 탐색 상세 화면 완료
  BeMe/BeMe.xcodeproj/project.pbxproj
  BeMe/BeMe/Assets.xcassets/btnMore24.imageset/Contents.json
  BeMe/BeMe/CustomActionSheet/Storyboard/CustomActionSheet.storyboard
  BeMe/BeMe/CustomActionSheet/VC/CustomActionSheet.swift
  BeMe/BeMe/Explore/Cells/AnswerTVC.swift
  BeMe/BeMe/Explore/Cells/ArticleTVC.swift
  BeMe/BeMe/Explore/Cells/DetailMoreTVC.swift
  BeMe/BeMe/Explore/Storyboards/Explore.storyboard
  BeMe/BeMe/Explore/VCs/ExploreDetailVC.swift
  BeMe/BeMe/Explore/VCs/ExploreVC.swift
  BeMe/BeMe/Extensions/UITableView+Extensions.swift
  BeMe/BeMe/Extensions/UIView+Extensions.swift
  BeMe/Podfile.lock
Labels: view, 재용

#52 feature/#45 : 애니메이션 구현완료, 카드 뷰 수정 완료
  BeMe/BeMe/Following/Cells/FollowCardCVC.swift
  BeMe/BeMe/Following/Cells/FollowPeopleCVC.swift
  BeMe/BeMe/Following/Cells/FollowUpperCVC.swift
  BeMe/BeMe/Following/Storyboards/Following.storyboard
  BeMe/BeMe/Following/VCs/FollowingVC.swift
Labels: 윤재

#54 Paging 생각보다 복잡하군요
  BeMe/BeMe/Explore/Storyboards/Explore.storyboard
  BeMe/BeMe/Explore/VCs/ExploreVC.swift
  BeMe/Podfile.lock
Labels: bug, view, 재용

#57 Feature/#53
  BeMe/BeMe.xcodeproj/project.pbxproj
  BeMe/BeMe/Extensions/UITextField+Extensions.swift
  BeMe/BeMe/Following/Cells/FollowUpperCVC.swift
  BeMe/BeMe/Following/Storyboards/Following.storyboard
  BeMe/BeMe/Following/VCs/FollowingVC.swift
  BeMe/BeMe/Search/Cells/SearchNewTVC.swift
  BeMe/BeMe/Search/Cells/SearchRecentTVC.swift
  BeMe/BeMe/Search/Storyboards/Search.storyboard
  BeMe/BeMe/Search/VCs/SearchVC.swift
Labels: view, 윤재

#59 Feature/#58 로그인, 회원가입 뷰 완료
  BeMe/BeMe.xcodeproj/project.pbxproj
  BeMe/BeMe/Extensions/String+Extensions.swift
  BeMe/BeMe/Extensions/UITextField+Extensions.swift
  BeMe/BeMe/Info.plist
  BeMe/BeMe/LogIn/Storyboards/LogIn.storyboard
  BeMe/BeMe/LogIn/VCs/LogInVC.swift
  BeMe/BeMe/Search/Storyboards/Search.storyboard
  BeMe/BeMe/SignUp/Storyboards/SignUp.storyboard
  BeMe/BeMe/SignUp/VCs/SignUpControlVC.swift
  BeMe/BeMe/SignUp/VCs/SignUpPVC.swift
  BeMe/BeMe/SignUp/VCs/SignUpProfileVC.swift
  BeMe/BeMe/SignUp/VCs/SignUpVC.swift
  BeMe/BeMe/UnderTab/Storyboards/UnderTab.storyboard
  BeMe/Podfile.lock
Labels: 윤재

#61 feature/#60 : 로그인, 회원가입 서버 완료
  BeMe/BeMe.xcodeproj/project.pbxproj
  BeMe/BeMe/APIConstants.swift
  BeMe/BeMe/APIService/APIConstants.swift
  BeMe/BeMe/APIService/LogIn/LogInService.swift
  BeMe/BeMe/APIService/NetworkResult.swift
  BeMe/BeMe/APIService/SignUp/SignUpService.swift
  BeMe/BeMe/LogIn/VCs/LogInVC.swift
  BeMe/BeMe/Model/GenericResponse.swift
  BeMe/BeMe/Model/LogIn/LogInData.swift
  BeMe/BeMe/Model/SignUp/SignUpData.swift
  BeMe/BeMe/SignUp/Storyboards/SignUp.storyboard
  BeMe/BeMe/SignUp/VCs/SignUpControlVC.swift
  BeMe/BeMe/SignUp/VCs/SignUpProfileVC.swift
  BeMe/BeMe/SignUp/VCs/SignUpVC.swift
Labels: server, 윤재

#78 :bulb: 글쓰기 서버 구현 완료
  BeMe/BeMe.xcodeproj/project.pbxproj
  BeMe/BeMe/APIService/APIConstants.swift
  BeMe/BeMe/APIService/Answer/AnswerModifyService.swift
  BeMe/BeMe/APIService/Answer/AnswerRegistService.swift
  BeMe/BeMe/Answer/Storyboards/Answer.storyboard
  BeMe/BeMe/Answer/VCs/AnswerVC.swift
  BeMe/BeMe/Assets.xcassets/btnUnlock.imageset/Contents.json
  BeMe/BeMe/Assets.xcassets/btnUnlock.imageset/btnUnlock.png
  BeMe/BeMe/Assets.xcassets/btnUnlock.imageset/btnUnlock@2x.png
  BeMe/BeMe/Assets.xcassets/btnUnlock.imageset/btnUnlock@3x.png
  BeMe/BeMe/Home/Cells/NewCardCVC.swift
  BeMe/BeMe/Home/Cells/PastCardCVC.swift
  BeMe/BeMe/Home/VCs/HomeVC+UnderAlert.swift
  BeMe/BeMe/Home/VCs/HomeVC.swift
Labels: 윤재

#93 feautre/#86 팔로워 삭제 제외 모두 구현 완료
  BeMe/BeMe.xcodeproj/project.pbxproj
  BeMe/BeMe/Following/Cells/FollowCardCVC.swift
  BeMe/BeMe/Following/Cells/FollowerListCVC.swift
  BeMe/BeMe/Following/Cells/FollowingListCVC.swift
  BeMe/BeMe/Following/Storyboards/FollowSearch.storyboard
  BeMe/BeMe/Following/VCs/FollowSearchVC.swift
  BeMe/BeMe/Following/VCs/FollowerSearchVC.swift
  BeMe/BeMe/Following/VCs/FollowingSearchPVC.swift
  BeMe/BeMe/Following/VCs/FollowingSearchVC.swift
  BeMe/BeMe/Following/VCs/FollowingVC.swift
  BeMe/BeMe/Home/Storyboards/HomeLottietest.storyboard
  BeMe/BeMe/Home/VCs/HomeLottietestVC.swift
  BeMe/BeMe/SupportFiles/animation_test.json
  BeMe/BeMe/SupportFiles/data1.json
Labels: 윤재

#96 feature/#94 팔로워 삭제하기 제외 완료
  BeMe/BeMe.xcodeproj/project.pbxproj
  BeMe/BeMe/APIService/APIConstants.swift
  BeMe/BeMe/APIService/FindPeople/FindDeleteSearchService.swift
  BeMe/BeMe/APIService/FindPeople/FindHistoryService.swift
  BeMe/BeMe/APIService/Following/FollowerDeleteService.swift
  BeMe/BeMe/Assets.xcassets/icFollowDelete.imageset/Contents.json
  BeMe/BeMe/Assets.xcassets/icFollowDelete.imageset/icFollowDelete.png
  BeMe/BeMe/Assets.xcassets/icFollowDelete.imageset/icFollowDelete@2x.png
  BeMe/BeMe/Assets.xcassets/icFollowDelete.imageset/icFollowDelete@3x.png
  BeMe/BeMe/CustomActionSheet/Model/AlertLabels.swift
  BeMe/BeMe/Following/Cells/FollowerListCVC.swift
  BeMe/BeMe/Following/Storyboards/FollowSearch.storyboard
  BeMe/BeMe/Following/VCs/FollowSearchVC.swift
  BeMe/BeMe/Following/VCs/FollowerSearchVC.swift
  BeMe/BeMe/Model/FindPeople/SearchHistoryData.swift
  BeMe/BeMe/Mypage/Storyboards/Mypage.storyboard
  BeMe/BeMe/Search/Cells/SearchRecentTVC.swift
  BeMe/BeMe/Search/Storyboards/Search.storyboard
  BeMe/BeMe/Search/VCs/SearchVC.swift
  BeMe/BeMe/UnderTab/VCs/UnderTabBarController.swift
Labels: 윤재

#101 Feature/#100
  BeMe/BeMe.xcodeproj/project.pbxproj
  BeMe/BeMe/APIService/APIConstants.swift
  BeMe/BeMe/APIService/SignUp/SignUpDuplicateService.swift
  BeMe/BeMe/Assets.xcassets/btnCheckBox.imageset/Contents.json
  BeMe/BeMe/Assets.xcassets/btnCheckBox.imageset/btnCheckBox.png
  BeMe/BeMe/Assets.xcassets/btnCheckBox.imageset/btnCheckBox@2x.png
  BeMe/BeMe/Assets.xcassets/btnCheckBox.imageset/btnCheckBox@3x.png
  BeMe/BeMe/Assets.xcassets/btnCheckBoxBlank.imageset/Contents.json
  BeMe/BeMe/Assets.xcassets/btnCheckBoxBlank.imageset/btnCheckBoxBlank.png
  BeMe/BeMe/Assets.xcassets/btnCheckBoxBlank.imageset/btnCheckBoxBlank@2x.png
  BeMe/BeMe/Assets.xcassets/btnCheckBoxBlank.imageset/btnCheckBoxBlank@3x.png
  BeMe/BeMe/CustomViews/CustomEmtpyView.swift
  BeMe/BeMe/CustomViews/CustomLoadingView.swift
  BeMe/BeMe/Extensions/UIColor+Extensions.swift
  BeMe/BeMe/Following/VCs/FollowerSearchVC.swift
  BeMe/BeMe/Following/VCs/FollowingSearchVC.swift
  BeMe/BeMe/Following/VCs/FollowingVC.swift
  BeMe/BeMe/Home/FlowLayouts/HomeCardCollectionView.swift
  BeMe/BeMe/Home/Storyboards/Home.storyboard
  BeMe/BeMe/Home/VCs/HomeVC.swift
  BeMe/BeMe/LogIn/Storyboards/LogIn.storyboard
  BeMe/BeMe/LogIn/VCs/LogInVC.swift
  BeMe/BeMe/Model/SignUp/SignUpDuplicateData.swift
  BeMe/BeMe/Search/VCs/SearchVC.swift
  BeMe/BeMe/SignUp/Storyboards/SignUp.storyboard
  BeMe/BeMe/SignUp/VCs/SignUpAgreeVC.swift
  BeMe/BeMe/SignUp/VCs/SignUpControlVC.swift
  BeMe/BeMe/SignUp/VCs/SignUpCropVC.swift
  BeMe/BeMe/SignUp/VCs/SignUpNoticeVC.swift
  BeMe/BeMe/SignUp/VCs/SignUpPVC.swift
  BeMe/BeMe/SignUp/VCs/SignUpProfileVC.swift
  BeMe/BeMe/SignUp/VCs/SignUpVC.swift
Labels: view, 윤재

#108 Feature/#102
  BeMe/BeMe.xcodeproj/project.pbxproj
  BeMe/BeMe/Assets.xcassets/onboarding01.imageset/Contents.json
  BeMe/BeMe/Assets.xcassets/onboarding01.imageset/onboarding01.png
  BeMe/BeMe/Assets.xcassets/onboarding01.imageset/onboarding01@2x.png
  BeMe/BeMe/Assets.xcassets/onboarding01.imageset/onboarding01@3x.png
  BeMe/BeMe/Assets.xcassets/onboarding02.imageset/Contents.json
  BeMe/BeMe/Assets.xcassets/onboarding02.imageset/onboarding02.png
  BeMe/BeMe/Assets.xcassets/onboarding02.imageset/onboarding02@2x.png
  BeMe/BeMe/Assets.xcassets/onboarding02.imageset/onboarding02@3x.png
  BeMe/BeMe/Assets.xcassets/onboarding03.imageset/Contents.json
  BeMe/BeMe/Assets.xcassets/onboarding03.imageset/onboarding03.png
  BeMe/BeMe/Assets.xcassets/onboarding03.imageset/onboarding03@2x.png
  BeMe/BeMe/Assets.xcassets/onboarding03.imageset/onboarding03@3x.png
  BeMe/BeMe/Assets.xcassets/onboarding04.imageset/Contents.json
  BeMe/BeMe/Assets.xcassets/onboarding04.imageset/onboarding04.png
  BeMe/BeMe/Assets.xcassets/onboarding04.imageset/onboarding04@2x.png
  BeMe/BeMe/Assets.xcassets/onboarding04.imageset/onboarding04@3x.png
  BeMe/BeMe/Extensions/UIColor+Extensions.swift
  BeMe/BeMe/Following/Cells/FollowCardCVC.swift
  BeMe/BeMe/Following/Cells/FollowNotAnsweredCVC.swift
  BeMe/BeMe/Following/Storyboards/Following.storyboard
  BeMe/BeMe/Following/VCs/FollowingVC.swift
  BeMe/BeMe/Home/VCs/HomeVC.swift
  BeMe/BeMe/Onboarding/Storyboards/Onboarding.storyboard
  BeMe/BeMe/Onboarding/VCs/OnboardingFirstVC.swift
  BeMe/BeMe/Onboarding/VCs/OnboardingFourthVC.swift
  BeMe/BeMe/Onboarding/VCs/OnboardingPVC.swift
  BeMe/BeMe/Onboarding/VCs/OnboardingSecondVC.swift
  BeMe/BeMe/Onboarding/VCs/OnboardingThirdVC.swift
  BeMe/BeMe/Onboarding/VCs/OnboardingVC.swift
  BeMe/Podfile.lock
Labels: 윤재

#111 Feature/#109
  BeMe/BeMe.xcodeproj/project.pbxproj
  BeMe/BeMe/Assets.xcassets/imgClause.imageset/Contents.json
  BeMe/BeMe/Assets.xcassets/imgClause.imageset/imgClause.png
  BeMe/BeMe/Assets.xcassets/imgClause.imageset/imgClause@2x.png
  BeMe/BeMe/Assets.xcassets/imgClause.imageset/imgClause@3x.png
  BeMe/BeMe/Assets.xcassets/imgClause2.imageset/Contents.json
  BeMe/BeMe/Assets.xcassets/imgClause2.imageset/imgClause.png
  BeMe/BeMe/Assets.xcassets/imgClause2.imageset/imgClause@2x.png
  BeMe/BeMe/Assets.xcassets/imgClause2.imageset/imgClause@3x.png
  BeMe/BeMe/CustomViews/CustomLoadingView.swift
  BeMe/BeMe/Extensions/UILabel+extensions.swift
  BeMe/BeMe/Following/Cells/FollowCardCVC.swift
  BeMe/BeMe/Following/Cells/FollowNotAnsweredCVC.swift
  BeMe/BeMe/Following/Storyboards/Following.storyboard
  BeMe/BeMe/Following/VCs/FollowerSearchVC.swift
  BeMe/BeMe/Following/VCs/FollowingSearchVC.swift
  BeMe/BeMe/Following/VCs/FollowingVC.swift
  BeMe/BeMe/Home/Cells/NewCardCVC.swift
  BeMe/BeMe/Home/VCs/HomeVC.swift
  BeMe/BeMe/Info.plist
  BeMe/BeMe/LogIn/Storyboards/LogIn.storyboard
  BeMe/BeMe/LogIn/VCs/LogInVC.swift
  BeMe/BeMe/Model/Following/FollowingAnswersData.swift
  BeMe/BeMe/SignUp/Storyboards/SignUp.storyboard
  BeMe/BeMe/SignUp/VCs/SignUpAgreeVC.swift
  BeMe/BeMe/SupportFiles/Fonts/GmarketSansTTFBold.ttf
  BeMe/BeMe/SupportFiles/Fonts/GmarketSansTTFLight.ttf
  BeMe/BeMe/SupportFiles/Fonts/GmarketSansTTFMedium.ttf
Labels: view

#143 :hammer: 여러가지 버그 수정
  BeMe/BeMe/Answer/VCs/AnswerVC.swift
  BeMe/BeMe/Following/Cells/FollowNotAnsweredCVC.swift
  BeMe/BeMe/Following/Storyboards/Following.storyboard
  BeMe/BeMe/Following/VCs/FollowingVC.swift
  BeMe/BeMe/Home/VCs/HomeVC+UnderAlert.swift
  BeMe/BeMe/Home/VCs/HomeVC.swift
  BeMe/BeMe/Info.plist
  BeMe/BeMe/OthersPage/Cells/OthersPageCVC.swift
  BeMe/BeMe/OthersPage/VCs/OthersPageVC.swift
Labels: view, 윤재
